app = "lifeplace-frontend"
primary_region = "dfw" # Change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  REACT_APP_API_URL = "https://lifeplace-backend.fly.dev/api"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512