# Generated by Django 5.1.7 on 2025-03-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_alter_eventtype_description_event_eventfile_and_more"),
        ("products", "0001_initial"),
        ("questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_flows",
                        to="events.eventtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("INTRO", "Introduction"),
                            ("EVENT_TYPE", "Event Type Selection"),
                            ("DATE", "Date Selection"),
                            ("QUESTIONNAIRE", "Questionnaire"),
                            ("PRODUCT", "Product Selection"),
                            ("ADDON", "Add-on Selection"),
                            ("SUMMARY", "Booking Summary"),
                            ("PAYMENT", "Payment"),
                            ("CONFIRMATION", "Confirmation"),
                            ("CUSTOM", "Custom Step"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instructions for the client"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(help_text="Display order of this step"),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="bookingflow.bookingflow",
                    ),
                ),
            ],
            options={
                "ordering": ["booking_flow", "order"],
                "unique_together": {("booking_flow", "order")},
            },
        ),
        migrations.CreateModel(
            name="CustomStepConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html_content", models.TextField(blank=True)),
                ("use_react_component", models.BooleanField(default=False)),
                ("component_name", models.CharField(blank=True, max_length=255)),
                ("component_props", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.OneToOneField(
                        limit_choices_to={"step_type": "CUSTOM"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_config",
                        to="bookingflow.bookingstep",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DateStepConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_days_in_future", models.PositiveIntegerField(default=1)),
                ("max_days_in_future", models.PositiveIntegerField(default=365)),
                ("allow_time_selection", models.BooleanField(default=True)),
                (
                    "buffer_before_event",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer time in minutes before event"
                    ),
                ),
                (
                    "buffer_after_event",
                    models.PositiveIntegerField(
                        default=0, help_text="Buffer time in minutes after event"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.OneToOneField(
                        limit_choices_to={"step_type": "DATE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_config",
                        to="bookingflow.bookingstep",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductStepConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_selection", models.PositiveIntegerField(default=0)),
                (
                    "max_selection",
                    models.PositiveIntegerField(
                        default=0, help_text="0 means unlimited"
                    ),
                ),
                (
                    "selection_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Selection"),
                            ("MULTIPLE", "Multiple Selection"),
                        ],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step",
                    models.OneToOneField(
                        limit_choices_to={"step_type__in": ["PRODUCT", "ADDON"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_config",
                        to="bookingflow.bookingstep",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductStepItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_highlighted", models.BooleanField(default=False)),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="If set, overrides the product's default price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True,
                        help_text="If set, overrides the product's default description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_items",
                        to="bookingflow.productstepconfiguration",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_items",
                        to="products.productoption",
                    ),
                ),
            ],
            options={
                "ordering": ["config", "order"],
                "unique_together": {("config", "order")},
            },
        ),
        migrations.AddField(
            model_name="productstepconfiguration",
            name="products",
            field=models.ManyToManyField(
                related_name="booking_step_configs",
                through="bookingflow.ProductStepItem",
                to="products.productoption",
            ),
        ),
        migrations.CreateModel(
            name="QuestionnaireStepConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_all_fields", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_step_configs",
                        to="questionnaires.questionnaire",
                    ),
                ),
                (
                    "step",
                    models.OneToOneField(
                        limit_choices_to={"step_type": "QUESTIONNAIRE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_config",
                        to="bookingflow.bookingstep",
                    ),
                ),
            ],
        ),
    ]
