# Generated by Django 5.1.7 on 2025-05-22 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookingflow", "0001_initial"),
        ("workflows", "0002_workflowstage_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingflow",
            name="workflow_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Workflow template to assign to events created through this booking flow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_flows",
                to="workflows.workflowtemplate",
            ),
        ),
    ]
