# Generated by Django 5.1.7 on 2025-05-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstage",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="progression_condition",
            field=models.CharField(
                blank=True,
                help_text="Condition required to progress (QUOTE_ACCEPTED, PAYMENT_RECEIVED, etc.)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="required_tasks_completed",
            field=models.BooleanField(
                default=False,
                help_text="Require all associated tasks to be completed before progressing",
            ),
        ),
        migrations.AlterField(
            model_name="workflowstage",
            name="automation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMAIL", "Send Email"),
                    ("TASK", "Create Task"),
                    ("QUOTE", "Generate Quote"),
                    ("CONTRACT", "Generate Contract"),
                    ("REMINDER", "Send Reminder"),
                    ("NOTIFICATION", "Send Notification"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstage",
            name="trigger_time",
            field=models.CharField(
                blank=True,
                help_text="When to trigger automation (ON_CREATION, AFTER_1_DAY, AFTER_3_DAYS, etc.)",
                max_length=255,
            ),
        ),
    ]
