# Generated by Django 5.1.7 on 2025-03-20 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("currency", models.CharField(default="PHP", max_length=3)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "type",
                    models.CharField(
                        choices=[("PRODUCT", "Product"), ("PACKAGE", "Package")],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("allow_multiple", models.BooleanField(default=False)),
                ("has_excess_hours", models.BooleanField(default=False)),
                ("included_hours", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "excess_hour_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.eventtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("max_uses", models.PositiveIntegerField(blank=True, null=True)),
                ("current_uses", models.PositiveIntegerField(default=0)),
                (
                    "applicable_products",
                    models.ManyToManyField(blank=True, to="products.productoption"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
