# Build stage
FROM node:18-alpine as build

WORKDIR /app

# Copy shared code first
COPY ../shared ./src/shared

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Nginx image is used in docker-compose.prod.yml